controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController



joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0


arm_controller:
  ros__parameters:
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
      - Joint7

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    open_loop_control: true
    allow_nonzero_velocity_at_trajectory_end: true

    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.05
      Joint1:
        goal: 0.05
      Joint2:
        goal: 0.05
      Joint3:
        goal: 0.05
      Joint4:
        goal: 0.05
      Joint5:
        goal: 0.05
      Joint6:
        goal: 0.05
      Joint7:
        goal: 0.05

